//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvventoWrapperServiceClient.AvventoServiceEvents {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AvventoServiceEvents.IAvventoServiceEvents", CallbackContract=typeof(AvventoWrapperServiceClient.AvventoServiceEvents.IAvventoServiceEventsCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAvventoServiceEvents {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAvventoServiceEvents/OnDisplayUpdate")]
        void OnDisplayUpdate(string response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAvventoServiceEvents/OnDisplayUpdate")]
        System.Threading.Tasks.Task OnDisplayUpdateAsync(string response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAvventoServiceEventsCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAvventoServiceEvents/DisplayNotification")]
        void DisplayNotification(string response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAvventoServiceEventsChannel : AvventoWrapperServiceClient.AvventoServiceEvents.IAvventoServiceEvents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AvventoServiceEventsClient : System.ServiceModel.DuplexClientBase<AvventoWrapperServiceClient.AvventoServiceEvents.IAvventoServiceEvents>, AvventoWrapperServiceClient.AvventoServiceEvents.IAvventoServiceEvents {
        
        public AvventoServiceEventsClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AvventoServiceEventsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AvventoServiceEventsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AvventoServiceEventsClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AvventoServiceEventsClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void OnDisplayUpdate(string response) {
            base.Channel.OnDisplayUpdate(response);
        }
        
        public System.Threading.Tasks.Task OnDisplayUpdateAsync(string response) {
            return base.Channel.OnDisplayUpdateAsync(response);
        }
    }
}
