//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvventoWrapperTestClientGUI.AvventoServiceWrapperReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AvventoServiceWrapperReference.IAvventoService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAvventoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvventoService/LoginAction", ReplyAction="http://tempuri.org/IAvventoService/LoginActionResponse")]
        string LoginAction(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAvventoService/LoginAction", ReplyAction="http://tempuri.org/IAvventoService/LoginActionResponse")]
        System.Threading.Tasks.Task<string> LoginActionAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IAvventoService/DataDownloadAction", ReplyAction="http://tempuri.org/IAvventoService/DataDownloadActionResponse")]
        byte[] DataDownloadAction(string actionQuery);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IAvventoService/DataDownloadAction", ReplyAction="http://tempuri.org/IAvventoService/DataDownloadActionResponse")]
        System.Threading.Tasks.Task<byte[]> DataDownloadActionAsync(string actionQuery);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IAvventoService/SubmitAction", ReplyAction="http://tempuri.org/IAvventoService/SubmitActionResponse")]
        string SubmitAction(string actionQuery);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IAvventoService/SubmitAction", ReplyAction="http://tempuri.org/IAvventoService/SubmitActionResponse")]
        System.Threading.Tasks.Task<string> SubmitActionAsync(string actionQuery);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IAvventoService/LogoutAction", ReplyAction="http://tempuri.org/IAvventoService/LogoutActionResponse")]
        void LogoutAction();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IAvventoService/LogoutAction", ReplyAction="http://tempuri.org/IAvventoService/LogoutActionResponse")]
        System.Threading.Tasks.Task LogoutActionAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IAvventoService/Version", ReplyAction="http://tempuri.org/IAvventoService/VersionResponse")]
        string Version();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IAvventoService/Version", ReplyAction="http://tempuri.org/IAvventoService/VersionResponse")]
        System.Threading.Tasks.Task<string> VersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAvventoServiceChannel : AvventoWrapperTestClientGUI.AvventoServiceWrapperReference.IAvventoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AvventoServiceClient : System.ServiceModel.ClientBase<AvventoWrapperTestClientGUI.AvventoServiceWrapperReference.IAvventoService>, AvventoWrapperTestClientGUI.AvventoServiceWrapperReference.IAvventoService {
        
        public AvventoServiceClient() {
        }
        
        public AvventoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AvventoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AvventoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AvventoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoginAction(string userName, string password) {
            return base.Channel.LoginAction(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginActionAsync(string userName, string password) {
            return base.Channel.LoginActionAsync(userName, password);
        }
        
        public byte[] DataDownloadAction(string actionQuery) {
            return base.Channel.DataDownloadAction(actionQuery);
        }
        
        public System.Threading.Tasks.Task<byte[]> DataDownloadActionAsync(string actionQuery) {
            return base.Channel.DataDownloadActionAsync(actionQuery);
        }
        
        public string SubmitAction(string actionQuery) {
            return base.Channel.SubmitAction(actionQuery);
        }
        
        public System.Threading.Tasks.Task<string> SubmitActionAsync(string actionQuery) {
            return base.Channel.SubmitActionAsync(actionQuery);
        }
        
        public void LogoutAction() {
            base.Channel.LogoutAction();
        }
        
        public System.Threading.Tasks.Task LogoutActionAsync() {
            return base.Channel.LogoutActionAsync();
        }
        
        public string Version() {
            return base.Channel.Version();
        }
        
        public System.Threading.Tasks.Task<string> VersionAsync() {
            return base.Channel.VersionAsync();
        }
    }
}
